spring:
  jackson:
      time-zone: America/Sao_Paulo
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  data:
    mongodb:
      uri: ${mongodb.uri}
      authentication-database: admin
      auto-index-creation: true
      write-concern: MAJORITY
      read-preference: primary
      grid-fs-database: gridfs

server:
  port: 5200

paypal:
  api:
    url: https://api.paypal.com
  webhook:
    id: ${PAYPAL_WEBHOOK_ID}
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_CLIENT_SECRET}
