version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: dragoniteDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=soder
      - MONGO_INITDB_ROOT_PASSWORD=soder1989
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
